---
title: "Extract Land Cover"
author: "David Hope"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Extract Land Cover}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=F, echo=T}
knitr::opts_chunk$set(
  eval=T,
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
library(sf)
library(spsurvey)
library(glue)
library(BASSr)
library(raster)
library(rlang)
```

```{r load-hexes}
test_sa <- c("0322", "0740", "0404","0165","0247","0197")
allhexes <- read_rds(glue::glue("{here::here()}/output/NOntario_BASS_hexes.rds"))
studyareas <-  allhexes$StudyAreas%>% filter(grepl(glue_collapse( test_sa,"|"), StudyAreaID))
samplehexes <- allhexes$SampleUnits%>% filter(grepl(glue_collapse( test_sa,"|"), StudyAreaID))
rm(allhexes)
samplehexes1 <- samplehexes %>% filter(StudyAreaID=="ONT_SA_0197")
sa1 <- studyareas %>% filter(StudyAreaID=="ONT_SA_0197")
```

```{r extract-landcover, eval=F}
lcc2015 <- raster("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SANDBOX/dhdev/OnBMS/spatial/NontariobrandtLCC2015_reproj.tif")


sa1 <- studyareas %>% filter(StudyAreaID==unique(studyareas$StudyAreaID)[[1]])
sa1_lcc <- lcc2015 %>% crop(.,st_buffer(sa1, 1000)) %>% mask(st_buffer(sa1, 1000))

rm(lcc2015)
f_ <- function(x,...){x %>% 
  as_tibble() %>% 
  group_by(value) %>% summarize(n=n()) %>% ungroup %>% 
  mutate(p = n/sum(n),
         id = as.character( glue::glue("LC{str_pad(value,2, pad=0)}")) )%>% 
    dplyr::select(id, p) %>% pivot_wider(names_from = id, 
                                         values_from = p)
         }
library(raster)
beginCluster(8)
sa1_samples_lcc <- raster::extract( sa1_lcc,samplehexes1,fun = f_, df = F, sp =F)


study_hexes_lcc2015 <- bind_rows(sa1_samples_lcc) %>% replace(is.na(.),0) %>% bind_cols(samplehexes1,.) %>% mutate(area = units::drop_units(st_area(.)*0.0001))

study_hexes_lcc2015_ha <- study_hexes_lcc2015 %>% 
  mutate_at(vars(matches("LC\\d")) , ~.*area) 
hex_centroids <- st_centroid(study_hexes_lcc2015_ha)

inlake <- extract(sa1_lcc, hex_centroids)
hex_centroids$inlake_YN <- ifelse(inlake == 18, TRUE, FALSE)

sa1_hex_lcc <- raster::extract( sa1_lcc,sa1,df=T)#,#fun = f_, df = T, sp =F)
endCluster()
study_area_lcc2015 <- sa1_hex_lcc$NontariobrandtLCC2015_reproj %>% f_ %>% 
   bind_cols(sa1,.)

```


```{r, eval=T}
sa1_lcc <- raster(glue::glue("{here::here()}/output/ONT_SA_0197.tif"))
# ggplot(samplehexes1) + 
#   geom_sf() + geom_sf(data = sa1, fill = NA) +
#   geom_sf(data = st_buffer(sa1, 1000), fill = NA)

plot(sa1_lcc)
plot(sa1["StudyAreaID"], add=T, col=NA)
plot(samplehexes1["StudyAreaID"], add=T, col=NA)
title("ONT_SA_0197")


```

```{r}
# cost_rast <- raster("~/Local_Workspace/Projects/BMS_ON/OnBMS/spatial/Ontario_North_MinCost.tif")
# sa1_cost <- cost_rast %>% crop(.,st_buffer(sa1, 1000)) %>% mask(st_buffer(sa1, 1000))

# plot(sa1_cost)
# plot(sa1["StudyAreaID"], add=T, col=NA)
# plot(samplehexes1["StudyAreaID"], add=T, col=NA)
# title(unique(studyareas$StudyAreaID)[[1]])

```


```{r, eval=F}
winter_secondary <- read_sf("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/SecondaryRoadsNOntario.shp")
primary_roads <-  read_sf("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/PrimaryRoadsNOnt.shp")

wr1 <- st_transform(winter_secondary, st_crs(hex_centroids)) %>% 
                                 st_intersection(st_buffer(sa1, 10000))
pr1 <- st_transform(primary_roads, st_crs(hex_centroids)) %>% 
                                 st_intersection(st_buffer(sa1, 10000))


sec_road_dist <- st_distance(hex_centroids,wr1,by_element = F ) %>% 
  apply(.,1,FUN = min, na.rm=T ) 


prim_road_dist <- st_distance(hex_centroids,pr1,by_element = F ) %>% 
  apply(.,1,FUN = min, na.rm=T )

# study_hexes_lcc2015$winter_sec_dist <- st_distance(hex_centroids,wr1,by_element = T ) 
# study_hexes_lcc2015$primary_dist <- st_distance(hex_centroids,pr1,by_element = T )

study_hexes_cost <- samplehexes1 %>% 
  mutate(winter_sec_dist = ifelse(length(sec_road_dist)!=nrow(.),5000,sec_road_dist),
         primary_dist = ifelse(length(prim_road_dist)!=nrow(.),5000,prim_road_dist),
         RawCost = case_when(
           (primary_dist <= 1000)~primary_dist,
           (winter_sec_dist<= 1000)~winter_sec_dist *2,
           (primary_dist > 1000) ~ 5000,
           (winter_sec_dist > 1000) ~ 5000,
           TRUE~NA_real_
         ),
         RawCost = RawCost) %>% 
  bind_cols(as_tibble(st_coordinates(hex_centroids))) %>% 
  left_join(as_tibble(hex_centroids) %>% dplyr::select(SampleUnitID, inlake_YN), by = "SampleUnitID") %>% 
  rename(INLAKE = inlake_YN)

sample_hexes_lcc <- study_hexes_lcc2015_ha %>% 
  bind_cols(as_tibble(st_coordinates(hex_centroids)))

write_rds(list(cost = study_hexes_cost, lcc = sample_hexes_lcc),
               "output/testhexes.rds")

```



```{r run-together, fig.width=12, fig.height=8}
# dat <- read_rds(glue::glue("{here::here()}/output/testhexes.rds"))
dat <- read_rds(here::here("output/studyArea_ONT_SA_0197_BassPrep.rds"))
fbr <- full_BASS_run(num_runs = 50,nsamples =  10,
              att = dat$landcover %>% as.data.frame() %>%
                dplyr::select(-geometry), 
              att.sp = st_centroid(dat$landcover), 
              HexID = SampleUnitID,q = T,
              cost = dat$cost %>% 
                as.data.frame() %>% dplyr::select(-geometry), 
              return_all = F)

hexes_BASSr <- samplehexes1 %>% left_join(fbr, by = "SampleUnitID")
# 
# plot(sa1_lcc)
# plot(hexes_BASSr["inclpr"], add=T)
# title(unique(studyareas$StudyAreaID)[[1]])


lccdf <- sa1_lcc %>% raster::as.data.frame(xy=T, long =T) %>% as_tibble() %>%
    filter(!is.na(value))

  pal_ <- viridis::viridis(19)
  names(pal_) <- as.character(1:19)


  lc <- ggplot() + geom_raster(data = lccdf, aes(x, y, fill = as.factor(value))) +
    scale_fill_manual(values = pal_) +
    geom_sf(data = sa1, fill = NA) +
    labs(x = "", y = "", fill = "LCC2015")
  
  inplt <- ggplot() + geom_sf(data = hexes_BASSr,aes(fill = inclpr) ) + scale_fill_viridis_c()
  library(patchwork)
  lc + inplt


d <- dat$landcover %>% as.data.frame() %>%
                dplyr::select(-geometry)
z <- function(df, g){
  df1 <- df %>% filter(LC01 == 0)
  df %>% group_by({{g}}, StudyAreaID) %>% summarize(mean(X))
}
z(d, SampleUnitID )

```


```{r rast-loc}
habLoc <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SANDBOX/dhdev/OnBMS/spatial/NontariobrandtLCC2015_reproj.tif"
roadloc1 <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/SecondaryRoadsNOntario.shp"
roadloc2 <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/PrimaryRoadsNOnt.shp"
```

```{r full-run-ex, eval=F}
fbr2 <- extract_habitat_cost(number_iterations = 3, n_samples_per_iter = 20, 
                             sa.rast.loc = here::here("output"),
                             rds.loc = here::here("output"),
                             sample_hexes = samplehexes,
                             study_area_hexes = studyareas, 
                             id = unique(studyareas$StudyAreaID)[[1]], 
                             id_col = StudyAreaID, 
                             hab_rast_location = habLoc, 
                             primary_roads = roadloc1, 
                             secondary_roads =roadloc2, 
                             return_all_ = F, load_hexes = T, 
                             write_hexes = F, quick = T )
```

```{r full-run, eval= F}
fbr_study_area_test <- map(unique(studyareas$StudyAreaID) ,
                           ~extract_habitat_cost(number_iterations = 100,
                                                 n_samples_per_iter = 20, 
                                                 sample_hexes = samplehexes, 
                                                 study_area_hexes = studyareas, 
                                                 id = .x, id_col = StudyAreaID,
                                                 hab_rast_location = habLoc,
                                                 primary_roads = roadloc1,
                                                 secondary_roads =roadloc2, 
                                                 return_all_ = T, quick = T,
                                                 load_hexes = T, write_hexes = F))

extra_area <- extract_habitat_cost(number_iterations = 100,
                                                 n_samples_per_iter = 20, 
                                                 sample_hexes = samplehexes, 
                                                 study_area_hexes = studyareas, 
                                                 id = "ONT_SA_0165", id_col = StudyAreaID,
                                                 hab_rast_location = habLoc,
                                                 primary_roads = roadloc1,
                                                 secondary_roads =roadloc2, 
                                                 return_all_ = T, quick = T,
                                                  load_hexes = F, write_hexes = T)
```



```{r ful-run-save, eval=F}
write_rds(fbr_study_area_test, "output/study_area_test_results.rds")
```

