---
title: "N Ontario Study Areas"
author: "David Hope"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{N Ontario Study Areas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message =F, warning=F}
knitr::opts_chunk$set(eval=F)
library(BASSr)
library(tidyverse)
library(patchwork)
library(sf)
# library(velox)
library(exactextractr)
library(raster)
ont.proj <- 3161
lcc2015 <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/lcc2015_hab/NontariobrandtLCC2015_reproj.tif"

r <- raster(lcc2015)
studyareas <- st_read(here::here("output/NOntario_BASS_StudyAreas.shp"))
brantStudyAreas <- read_rds(here::here("output/NONT_HexesWithinBrant.rds"))
ontario <- read_sf("//int.ec.gc.ca/Shares/C/CWS_ON/Shared_Data/Base_Data/Boundaries/Canada/canada.shp") %>%
  filter(PROV == "ON") %>%
  st_transform(st_crs(studyareas), partial = F, check = T)

# road_info <- read_rds(here::here("output/road_density_byHex_full.rds")) %>% 
#   mutate(p_pr = pr / saa,
#          p_sr = sr / saa,
#          wr = wr /saa)


study_area_hexagons_in_brandt <- studyareas %>% 
  dplyr::filter(StdyAID %in% brantStudyAreas$StudyAreaID) %>% 
  mutate(StudyAreaID = StdyAID)
```






```{r}


airports_official <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BASS_AccessLyrs/Airports_Official_FeaturesToPoints.shp") %>% filter(AIRPORT_TY != "Hospital Heliport")%>% st_transform(ont.proj)


airports_other <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BASS_AccessLyrs/Airports_Other_FeaturesToPoints.shp")%>% st_transform(ont.proj)

tourism <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BASS_AccessLyrs/TourismEstablishments_pt.shp")%>% st_transform(ont.proj)
primary_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/Primary1000.shp") %>% st_transform(ont.proj)
secondary_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/SecondaryOnlyBuff1k.shp")%>% st_transform(ont.proj)
road_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/Roads_1000_PriSec.shp")%>% st_transform(ont.proj)
winter_buff <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/WinterRoads_Buffer1k.shp")%>% st_transform(ont.proj)
habLoc <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SANDBOX/dhdev/OnBMS/spatial/NontariobrandtLCC2015_reproj.tif"


```


```{r, eval=F}

ontario_cost <- 
prepare_cost(truck_roads = primary_buffer, atv_roads = secondary_buffer, winter_roads = winter_buff, all_roads = road_buffer, airports = airports_official,basecamps = tourism, hexagons = study_area_hexagons_in_brandt, idcol_ = StudyAreaID, calc_roads = T)

StudyArea_CostModel <- 
estimate_cost_study_area(narus = 30, StudyAreas =  ontario_cost, 
                         pr  = p_pr, sr = p_sr, dist_base_sa = basecamps,
                         dist_airport_sa = airportdist_km, dist2airport_base = cabin_dist_to_air,
                         vars = cost_vars)


write_rds(list(StudyArea_CostVars = ontario_cost, StudyArea_CostModel = StudyArea_CostModel), "output/2020-02-05_StudyAreaCost.rds")
```

```{r}
modelrun <- read_rds(here::here("output/2020-02-05_StudyAreaCost.rds"))
ontario_cost <- modelrun$StudyArea_CostVars
 StudyArea_CostModel <- modelrun$StudyArea_CostModel
```


```{r}
ggplot(ontario_cost, aes(fill = p_sr)) + geom_sf() +
     ggspatial::annotation_scale(location = "bl", width_hint = 0.4) +
  labs(fill = "Proportion of Secondary Roads")
```

```{r}
ggplot(StudyArea_CostModel, aes(fill = log10(RawCost))) + 
  geom_sf() +
     ggspatial::annotation_scale(location = "bl", width_hint = 0.4) +
  labs(fill = "Raw Cost (log10)")
```


```{r}

sa_cent <- st_centroid(brantStudyAreas)

min_dist <- function(x,y){
   (st_distance(x, y, by_element = F) %>% 
  apply(., 1, FUN = min, na.rm=T) %>% as.numeric 
  ) /1000
}

brantStudyAreas_air <- brantStudyAreas %>% 
  left_join(road_info, by = c("StudyAreaID" = "StudyArea")) %>% 
  mutate(
  airportdist_km= min_dist(., airports_official),
  airport_other_km = min_dist(., airports_other),
  cabins  = min_dist(., tourism))

hist(brantStudyAreas_air$airportdist_km)

tst <- 
tourism %>% 
  st_nearest_feature(y = airports_official) 

tourism[c("nearest_airport", "airporttype", "airportID")] <- airports_official[tst, c("NAME", "AIRPORT_TY", "OGF_ID")] %>% as_tibble() %>% dplyr::select(-geometry)
tourism$dist_to_air <- min_dist(tourism, airports_official)

cabinTST <- 
brantStudyAreas_air %>% 
  st_nearest_feature(y = tourism) 


brantStudyAreas_air[c("NearestCabin", 
                      "CabinID",
                      "CabinTYPE",
                      "cabin_nearest_airport", 
                      "cabin_airporttype", 
                      "cabin_airportID",
                      "cabin_dist_to_air")]  <- as_tibble(tourism)[(cabinTST), c("OFFICIAL_N", "OGF_ID", 
                                                                         "CLASS_SUBT", 
                                                                         "nearest_airport", 
                                                                         "airporttype", 
                                                                         "airportID",
                                                                         "dist_to_air")]


nearest_airport <- brantStudyAreas_air %>% 
  st_nearest_feature(y = airports_official)


brantStudyAreas_air[c("nearest_airport", "airporttype", "airportID")] <- as_tibble(airports_official)[nearest_airport,
                                                                                                      c("NAME", 
                                                                                                        "AIRPORT_TY", 
                                                                                                        "OGF_ID")] 

```

```{r, eval=F}

cost_estimates_hexes <- estimate_cost_study_area(narus = 30, StudyAreas =  brantStudyAreas_air, 
                         pr  = p_pr, sr = p_sr, dist_base_sa = cabins,
                         dist_airport_sa = airportdist_km, dist2airport_base = cabin_dist_to_air,
                         vars = cost_vars)
write_rds(cost_estimates_hexes, "output/cost_estimates.rds")
 
```


```{r}
cost_estimates_hexes <- read_rds(here::here("output/cost_estimates.rds"))

cost_hexes <- cost_estimates_hexes %>% as_tibble() %>% 
  dplyr::select(-x) %>% 
  right_join(studyareas, by = c("StudyAreaID" = "StdyAID")) %>% 
  st_as_sf()
```



```{r}

 cost_hexes%>% 
  filter(!is.na(total_cost)) %>% 
  ggplot() + geom_sf(aes(fill = total_cost) )+ 
  scale_fill_viridis_c() +
     ggspatial::annotation_scale(location = "bl", width_hint = 0.4)+
  labs(fill = "Total Cost")


```


```{r}
  cost_hexes %>% 
filter(!is.na(total_cost)) %>% 
  ggplot() + geom_sf(aes(fill = total_truck_cost) )+ 
  scale_fill_viridis_c()
```

```{r}
  cost_hexes %>% 
  ggplot() + geom_sf(aes(fill = total_atv_cost) )+ 
  scale_fill_viridis_c()
```

```{r}
  cost_hexes %>% 
  ggplot() + geom_sf(aes(fill = total_heli_cost ) )+ 
  scale_fill_viridis_c() + 
  geom_sf(data = airports_official, colour = 'red') + 
  geom_sf(data = tourism, colour = 'grey', shape = 2, alpha = 0.5)
```


```{r}
 cost_hexes%>% 
  filter(total_cost < 30000) %>% 
  ggplot() + geom_sf(aes(fill = total_cost) )+ 
  scale_fill_viridis_c() +
  geom_sf(data = cost_hexes %>% filter(total_cost > 30000), fill = 'red')
```



```{r}

ggplot(cost_estimates_hexes, aes(p_pr, log10(total_cost))) + geom_point() + geom_smooth()
range(cost_estimates_hexes$total_cost)

```





```{r cost-function, eval=F}

prepare_cost <- function( truck_roads, atv_roads, winter_roads,all_roads, airports, basecamps, hexagons, idcol_,
                         calc_roads = T,
                         airport_cols =  c("NAME", "AIRPORT_TY", "OGF_ID"),
                         basecamp_cols = c("OFFICIAL_N", "OGF_ID", "CLASS_SUBT",
                                            "nearest_airport", 
                                            "airporttype", 
                                            "airportID",
                                            "dist_to_air")
                        
                         ){
  ids <- unique(hexagons[[as_label(enquo(idcol_))]]) # Hexagon IDs
  if(isTRUE(calc_roads)){
  #1 Calculate the proportion of each hexagon covered by roads
  hexagons_w_roads <- map_df(ids, getroaddensity, hexes = hexagons, wr = winter_buff,
               pr= truck_roads,sr = atv_roads, r = all_roads, idcol = idcol_) %>% 
     mutate(p_pr = pr / saa, # Covert to proportion of area
         p_sr = sr / saa,
         wr = wr /saa)
  } else{hexagons_w_roads <- hexagons}
  
  # Hexagon centroids
  hexagon_centroids <- st_centroid(hexagons_w_roads)

  min_dist <- function(x,y){
     (st_distance(x, y, by_element = F) %>% 
    apply(., 1, FUN = min, na.rm=T) %>% as.numeric 
    ) /1000
  }

  centroids_with_road_air <- hexagon_centroids %>% 
    mutate(
    airportdist_km= min_dist(., airports),
    basecamps  = min_dist(., basecamps))

  tst <- 
  basecamps %>% 
    st_nearest_feature(y = airports) 

basecamps[c("nearest_airport", "airporttype", "airportID")] <- airports[tst,airport_cols] %>% 
  as_tibble() %>% 
  dplyr::select(-geometry)
basecamps$dist_to_air <- min_dist(tourism, airports_official)

basecamp_order <- 
  centroids_with_road_air %>% 
  st_nearest_feature(y = basecamps) 


centroids_with_road_air[c("NearestCabin", 
                      "CabinID",
                      "CabinTYPE",
                      "cabin_nearest_airport", 
                      "cabin_airporttype", 
                      "cabin_airportID",
                      "cabin_dist_to_air")]  <- as_tibble(basecamps)[(basecamp_order), basecamp_cols]


nearest_airport <- centroids_with_road_air %>% 
  st_nearest_feature(y = airports_official)


centroids_with_road_air[c("nearest_airport", "airporttype", "airportID")] <- as_tibble(airports)[nearest_airport,
                                                                                                     airport_cols] 


left_join(hexagons, 
          dplyr::select(as_tibble(centroids_with_road_air), -geometry)
          )


}
all_costvars <- 
prepare_cost(truck_roads = NA, atv_roads = NA, winter_roads = NA, all_roads = NA, airports = airports_official, basecamps = tourism, hexagons =  study_area_hexagons_in_brandt %>% 
  left_join(road_info, by = c("StudyAreaID" = "StudyArea")),idcol_ = StudyAreaID, calc_roads = F )
data("cost_vars")
cost_est2 <- estimate_cost_study_area(narus = 30, StudyAreas =  all_costvars, 
                         pr  = p_pr, sr = p_sr, dist_base_sa = basecamps,
                         dist_airport_sa = airportdist_km, dist2airport_base = cabin_dist_to_air,
                         vars = cost_vars)

# write_rds(cost_est2, "output/2020-01-24_StudyArea_costs.rds")

```









































