---
title: "Sample Study Areas"
author: "David Hope"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Sample Study Areas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=F,warning=F}

knitr::opts_chunk$set(eval=T, fig.width = 8)
library(BASSr)
library(tidyverse)
library(patchwork)
theme_set(theme_minimal())

```

```{r}
lcc2015 <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/lcc2015_hab/NontariobrandtLCC2015_reproj.tif"

fbr_study_area_test <- read_rds(here::here("output/2020-01-28_fbr_studyarea2.rds"))

studyarea <- purrr::transpose(fbr_study_area_test)$study_area %>% do.call('c',.)
test_sa <-c("0322", "0740", "0404","0165","0247","0197")
allhexes <- read_rds(here::here("output/NOntario_BASS_hexes.rds"))
studyareas <-  allhexes$StudyAreas%>% filter(grepl(glue::glue_collapse( test_sa,"|"), StudyAreaID))
rm(allhexes)


studyareaMaps <- map(1:length(fbr_study_area_test), ~ggplot(fbr_study_area_test[[.x]]$inclusion_probs) + geom_sf(aes(fill = inclpr))  +
  labs(title = fbr_study_area_test[[.x]]$study_area) + scale_fill_viridis_c(limits = c(0,1)))

saplt <- ((studyareaMaps[[1]] | studyareaMaps[[2]] |studyareaMaps[[3]]) /
      (studyareaMaps[[4]] | studyareaMaps[[5]] | studyareaMaps[[6]] )) 

saplt <- studyareaMaps[[1]] + studyareaMaps[[2]] +studyareaMaps[[3]] +
      studyareaMaps[[4]] + studyareaMaps[[5]] + studyareaMaps[[6]] 

saplt + plot_layout(guides = "collect")

```




```{r, eval=F}

map(studyarea, ~genraster(id_col = StudyAreaID,
                          studyareas = studyareas,hab_rast_location = lcc2015,
                          id = .x, outpath =  "output",writeout = T))
genraster(id_col = StudyAreaID,
                          studyareas = studyareas,hab_rast_location = lcc2015,
                          id = "ONT_SA_0165", outpath =  "output",writeout = T)


```

```{r}
compareBASSPlots <- function(i) {
  r <- studyarea[i]
  x <- raster::raster(glue::glue("{here::here('output')}/{r}.tif")) %>%
    raster::as.data.frame(xy = T, long = T) %>%
    as_tibble() %>%
    filter(!is.na(value))

  pal_ <- viridis::viridis(19)
  names(pal_) <- as.character(1:19)


  lc <- ggplot() + geom_raster(data = x, aes(x, y, fill = as.factor(value))) +
    scale_fill_manual(values = pal_) +
    geom_sf(data = fbr_study_area_test[[i]]$inclusion_probs, fill = NA) +
    labs(x = "", y = "", fill = "LCC2015")

  baseplot <- ggplot(fbr_study_area_test[[i]]$inclusion_probs) +
    scale_fill_gradient(limit = c(0, 1)) +
    theme(axis.text = element_blank())

  legend_ <- cowplot::get_legend(baseplot)

  pr <- baseplot + geom_sf(aes(fill = inclpr)) + labs(title = "Inclusion Prob") +
    theme(legend.position = "none")

  ben <- baseplot + geom_sf(aes(fill = scale_ben)) + labs(title = "Benefit") +
    theme(legend.position = "none")

  cost <- baseplot + geom_sf(aes(fill = ScLogCost)) + labs(title = "Scaled Cost", fill = "")

  a <- ben + pr + cost + plot_layout(widths = c(1, 1, 1)) #+ plot_spacer() 

  (lc | a + plot_layout(guides = "collect", widths = c(1, 2))) +
    plot_annotation(title = fbr_study_area_test[[i]]$study_area) &
    theme(text = element_text("mono"))
}
```

```{r make-plot-pdf}
plots_test <- map(1:6, compareBASSPlots)
```

```{r, eval=F}
pdf(here::here("output/SamplePlots3.pdf"), family = 'mono', width = 17, height = 11)
for (p in plots_test) {
  plot(p)
}
dev.off()
```

```{r show-plots}
plots_test
```



```{r fbr-tran}
tr <- fbr_study_area_test %>% purrr::transpose()

ggplot(tr$inclusion_probs %>% do.call('rbind',.), aes(inclpr)) + facet_wrap(~StudyAreaID) +
  geom_density(fill = 'grey')
```


```{r, eval=F}
calculate_metrics <- function(i, lsm=NULL){
 r <- raster::raster(glue::glue("{here::here('output')}/{studyarea[i]}.tif"))
 r_df <- r %>%
    raster::as.data.frame(xy = T, long = T) %>%
    as_tibble() %>%
    filter(!is.na(value)) %>% group_by(value) %>% 
   summarize(pHab = n()/nrow(.)) %>% ungroup
if(!is_null(lsm)) {
  lscm_r <- landscapemetrics::calculate_lsm(r)
  return(list(r_df = r_df, lscm_r = lscm_r, study = studyarea[i]))
  }
return(list(r_df = r_df, study = studyarea[i]))
}


allMetrics <- map(1:5, calculate_metrics)



```

