---
title: "Spatial Works Sample Units"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spatial Works Sample Units}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=F, echo=T}
knitr::opts_chunk$set(
  eval=T,
  collapse = TRUE,
  fig.width = 8,
  fig.height = 8,
  warning = F, 
  message = F,
  comment = "#>"
)
library(tidyverse)
library(sf)
library(spsurvey)
library(glue)
library(BASSr)
library(raster)
library(rlang)
library(patchwork)
spatialworks <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BaldwinHexLandCov/Data/ExportedDataTables"

files_spatialworks <- list.files(path = spatialworks, pattern = ".csv")

files_study <- files_spatialworks[grepl("Study", x=files_spatialworks)]
files_sample <- files_spatialworks[grepl("Sample", x=files_spatialworks)]
read_SW <- function(lst, x){read_csv(paste(spatialworks, lst[grepl(x,lst)],sep="/" ), col_types = cols())}
FNLCID <- read_SW(files_spatialworks, "CLS_F")
LC15ID <- read_SW(files_spatialworks, "CLS_CLC2015")
LC10ID <- read_SW(files_spatialworks, "CLS_CLC2010")

lcc2015_codes <- read_csv(here::here("inst/extdata/LCC2010_LandCoverCodeDescriptions.csv"))
clrfile <- read_delim("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/CAN_NALCMS_LC_30m_LAEA_mmu12_urb05.clr", col_names = c("Value", "red", "green", "blue"), delim = " ") %>% 
  mutate(rgb = pmap_chr(.l = list(red, green, blue),
                    .f = rgb,maxColorValue = 255 )) %>% 
  left_join(lcc2015_codes, by = c("Value" = "LCC_CODE"))

brandtStudyAreas <- read_rds(here::here("output/NONT_HexesWithinBrant.rds"))
brandtStudyAreas_list <-  brandtStudyAreas$StudyAreaID
```

## Load in Sample units for example study areas

```{r}
test_sa <- c("0322", "0740", "0404","0165","0247","0197")

sampleunits <- map(list.files(here::here("output"), pattern = glue::glue("({glue_collapse(test_sa,  '|')}).+.rds"),full.names = T), read_rds)
cost <- purrr::transpose(sampleunits)$cost 
cost_df <- cost %>% do.call('rbind', .) %>% as_tibble() %>% dplyr::select(-geometry)
```

```{r}
cost[[1]] %>% ggplot(aes(fill = p_sr)) + geom_sf() + labs(title = sampleunits[[1]]$study_area) 
```


```{r, eval=T}
allhexes <- read_rds(here::here("output/NOntario_BASS_hexes.rds"))

SampleUnits_SW <- read_SW(files_sample, "SampleUnits") %>%
  # read_csv(paste(spatialworks, files_study[grepl("StudyAreas",files_study)],sep="/" ))  %>%
  rename(StudyAreaID = StdyAID, SampleUnitID = SmplUID) %>% 
  filter(grepl(glue_collapse( test_sa,"|"), StudyAreaID))



LCC2010 <-  read_SW(files_sample, "2010") %>%
  right_join(SampleUnits_SW, by = "ID")

LCC2015 <- read_SW(files_sample, "2015") %>%
  left_join(SampleUnits_SW, by = "ID")

FNLC <- read_SW(files_sample, "FNLC") %>%
  left_join(SampleUnits_SW, by = "ID")



ExampleSampleUnit_LandCover <- list(
  StudyAreas=st_as_sf(left_join(SampleUnits_SW, allhexes$SampleUnits)),
  LCC2010=LCC2010,
  LCC2015=LCC2015,
  FNLC=FNLC,
  BrandtStudyAreas = brandtStudyAreas_list)
```

```{r, eval =F}
write_rds(ExampleSampleUnit_LandCover, "output/ExampleSampleUnit_Landcover_SW.rds")



```

```{r}

ExampleSampleUnit_LandCover <- read_rds(here::here("output/ExampleSampleUnit_Landcover_SW.rds"))
list2env(ExampleSampleUnit_LandCover, envir = environment())
sa_s <- unique(ExampleSampleUnit_LandCover$StudyAreas$StudyAreaID)
r <- sa_s[1]
#here::here('output')

  pal_ <- clrfile$rgb
  names(pal_) <- as.character(clrfile$LCC_NAME)

# 
#   lc <- ggplot() + geom_raster(data = r, aes(x, y, fill = LCC_NAME)) +
#     scale_fill_manual(values = pal_) +
#     geom_sf(data = StudyArea_hexes$landcover, fill = NA) +
#     labs(x = "", y = "", fill = "LCC2015") + theme_linedraw()


raster_plot <- function(r, rast.loc, rast_id, hexes, lp= 'none'){
  name_r <- list.files(path = rast.loc, pattern = glue('{rast_id}.*{r}.tif$'), full.names =T)
  r_ <- raster::raster(glue::glue("{name_r}")) 
  if(rast_id != ""){
    r_ <- raster::projectRaster(r_, crs = proj4string(as(hexes, "Spatial")), method = 'ngb')
  }
  print(name_r)
    h <- hexes %>% filter(grepl(r, StudyAreaID))
  x <- r_ %>% raster::mask(h) %>% 
    raster::as.data.frame(xy = T, long = T) %>%
    as_tibble() %>%
    filter(!is.na(value)) %>% 
    left_join(lcc2015_codes, by = c("value" = "LCC_CODE"))
  # pal_ <- viridis::viridis(n_distinct(x$value))
  # names(pal_) <- as.character(unique(x$value))


   ggplot() + 
    scale_fill_manual(values = pal_) +
    geom_raster(data = x, aes(x, y, fill =LCC_NAME)) +
     geom_sf(data = h, fill = NA, colour = alpha('grety', alpha = 0.5)) +
    labs(x = "", y = "", fill = "", title = glue("{r} -- {rast_id}" )) +
    coord_sf() + theme_minimal()  +
     theme(legend.position = lp)
}

lgnd <- 
cowplot::get_legend(
ggplot(lcc2015_codes, aes(x = 1, y = 2,fill = LCC_NAME )) +
  geom_raster()+
  scale_fill_manual(values = pal_) +
  labs(fill= "CLC2015")
)

CLC2015_LCplots <- map(sa_s, raster_plot, 
            rast.loc = here::here("output"),
            rast_id =  "", 
            hexes = ExampleSampleUnit_LandCover$StudyAreas)
```


```{r, eval=T}


CLC2015_LCplots
  # pal_2 <- clrfile$rgb
  # names(pal_2) <- as.character(clrfile$LCC_NAME)
  #  scale_fill_manual(values = pal_) +
  #    
  #   CLC2015_LCplots[[1]] 

```

```{r}

wrap_plots(CLC2015_LCplots, guides = 'collect')

```


# Test BASS run on LCC 2015
```{r}

# clean_forBass <- function(df, s, f_vec = brandtStudyAreas_list, appended = ""){
#   df %>%
#     rename_at(.vars= vars(contains(glue::glue("{s}_"))),
#               .funs = ~glue::glue('LC{stringr::str_pad(gsub(glue::glue("{s}_"), "", .), width = 2, pad = 0)}{appended}'
#               ))  %>% filter(StudyAreaID %in% f_vec)
# }


LC2015_att <- clean_forBass(ExampleSampleUnit_LandCover$LCC2015, "CLC15")

WaterSA <- LC2015_att$SampleUnitID[LC2015_att$D_CLC15 == 18]

sa.cost <- cost_df %>%
  mutate(INLAKE = ifelse(SampleUnitID %in% WaterSA, T, F)) #%>% 
         # X = NA, Y = NA)




#
# ggplot(LC2015_att %>% filter(StudyAreaID %in% WaterSA),
#        aes(LC18/TOT_HA)) + geom_histogram(bins = 20)



LCC2015_BASS <- 
  map(test_sa, ~BASSr::full_BASS_run(num_runs = 50, nsamples = 10,
                                     att = LC2015_att %>%  filter(grepl(.x, StudyAreaID)) ,
                                     att.sp = st_centroid(ExampleSampleUnit_LandCover$StudyAreas %>%
                                                            filter(grepl(.x, StudyAreaID))),
                                     cost = sa.cost %>%  filter(grepl(.x, StudyAreaID)),
                                     return_all = T, 
                                     HexID_ = SampleUnitID, q = T) ) 
CLC2015 <- purrr::transpose(LCC2015_BASS) 
incpr_clc2015 <-CLC2015$inclusionPr%>% bind_rows() %>% 
  left_join(ExampleSampleUnit_LandCover$StudyAreas)
incpr_clc2015 %>%
  ggplot(aes(LogCost, benefit)) + geom_point() + facet_wrap(~StudyAreaID)

```



```{r}

plt_SU <- function(d,sa, fill_){
 d %>% filter(grepl(sa, StudyAreaID )) %>%
    st_as_sf() %>% 
    ggplot() +
    geom_sf(aes(fill = {{fill_}})) +
    scale_fill_viridis_c() +
    theme_minimal()
}


bens <- map(1:6, ~plt_SU(incpr_clc2015, sa_s[[.x]], scale_ben) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
inclpr_plt <- map(1:6, ~plt_SU(incpr_clc2015, sa_s[[.x]], inclpr) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
cost_plt <- map(1:6, ~plt_SU(incpr_clc2015, sa_s[[.x]], ScLogCost) + labs(title = sa_s[[.x]]))
bens[[1]] # + labs(fill = "Scaled\nBenefit")
inclpr_plt[[1]]#+ labs(fill = "")
cost_plt[[1]]+ scale_fill_viridis_c(direction = -1)#+ labs(fill = "")
```

```{r}
wrap_plots(bens, nrow =2, ncol = 3) + plot_layout(guides = 'collect')
```

```{r}
sampleunits[[4]]$cost %>% 
  plt_SU(sa = test_sa[[1]], fill_ = RawCost)

```


```{r}
# lc + bens[[1]] + inclpr_plt[[1]] + cost_plt[[1]]
```



## FNLC


```{r}
FNLC_att <- clean_forBass(FNLC, "FNLC")

WaterSA_FNLC <- FNLC_att$SampleUnitID[FNLC_att$D_FNLC == 1]
sa_cost_FNLC <- cost_df %>%
  mutate(INLAKE = ifelse(SampleUnitID %in% WaterSA_FNLC, T, F),
         X = NA, Y = NA)

FNLC_BASS <-  map(test_sa, ~BASSr::full_BASS_run(num_runs = 50, nsamples = 10,
                                     att = FNLC_att %>%  filter(grepl(.x, StudyAreaID)) ,
                                     att.sp = st_centroid(ExampleSampleUnit_LandCover$StudyAreas %>%
                                                            filter(grepl(.x, StudyAreaID))),
                                     cost = sa_cost_FNLC %>%  filter(grepl(.x, StudyAreaID)),
                                     return_all = T, HexID_ = SampleUnitID, q = T) ) 
FNLC_t <- purrr::transpose(FNLC_BASS) 
incpr_FNLC <-FNLC_t$inclusionPr%>% bind_rows() %>% 
  left_join(ExampleSampleUnit_LandCover$StudyAreas)


FNLC_LCplots <- map(sa_s, raster_plot, 
            rast.loc = 
              "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/ExampleStudyAreas",
            rast_id =  "FNLC", 
            hexes = ExampleSampleUnit_LandCover$StudyAreas)


```

```{r}

bensFNLC <- map(1:6, ~plt_SU(incpr_FNLC, sa_s[[.x]], scale_ben) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
inclpr_pltFNLC <- map(1:6, ~plt_SU(incpr_FNLC, sa_s[[.x]], inclpr) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
cost_pltFNLC <- map(1:6, ~plt_SU(incpr_FNLC, sa_s[[.x]], ScLogCost) + labs(title = sa_s[[.x]]))


```



```{r}

# plt_SA(FNLC_BASS$inclusionPr, benefit)
```

## LC2010
```{r}
CLC10_att <- clean_forBass(LCC2010, "CLC10")


WaterSA10 <- CLC10_att$SampleUnitID[CLC10_att$D_CLC10 == 18]

sa_cost10 <- cost_df %>%
  mutate(INLAKE = ifelse(SampleUnitID %in% WaterSA10, T, F),
         X = NA, Y = NA)

LC10_BASS <-  map(test_sa, ~BASSr::full_BASS_run(num_runs = 50, nsamples = 10,
                                     att = CLC10_att %>%  filter(grepl(.x, StudyAreaID)) ,
                                     att.sp = st_centroid(ExampleSampleUnit_LandCover$StudyAreas %>%
                                                            filter(grepl(.x, StudyAreaID))),
                                     cost = sa_cost10 %>%  filter(grepl(.x, StudyAreaID)),
                                     return_all = T, HexID_ = SampleUnitID, q = T) ) 

LC10_t <- purrr::transpose(LC10_BASS) 
incpr_CLC10 <-LC10_t$inclusionPr%>% bind_rows() %>% 
  left_join(ExampleSampleUnit_LandCover$StudyAreas)

```

```{r}

bens10 <- map(1:6, ~plt_SU(incpr_CLC10, sa_s[[.x]], scale_ben) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
inclpr_plt10 <- map(1:6, ~plt_SU(incpr_CLC10, sa_s[[.x]], inclpr) + labs(title = sa_s[[.x]]) + scale_fill_viridis_c(limits = c(0,1)))
cost_plt10 <- map(1:6, ~plt_SU(incpr_CLC10, sa_s[[.x]], ScLogCost) + labs(title = sa_s[[.x]]))


```


```{r}
CLC10_LCplots <- map(sa_s, raster_plot, 
            rast.loc = 
              "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/ExampleStudyAreas",
            rast_id =  "CLC10", 
            hexes = ExampleSampleUnit_LandCover$StudyAreas)
```



```{r, eval=F}
glue("({glue_collapse(sa_s, sep = ',')})")
write_rds(list(CLC2015_LCplots=CLC2015_LCplots,
CLC10_LCplots=CLC10_LCplots,
FNLC_LCplots=FNLC_LCplots,
bens=bens,
bens10=bens10,
bensFNLC=bensFNLC
), "output/exampleStudyAreaPlots.rds")
```


```{r, eval=F}

pdf(here::here("output/Example_StudyAreas.pdf"), family = 'mono', width = 17, height = 11)
for(i in 1:6){
print(CLC2015_LCplots[[i]] + CLC10_LCplots[[i]] + FNLC_LCplots[[i]]  +
  bens[[i]]+ bens10[[i]]+ bensFNLC[[i]] + plot_layout(nrow = 2, ncol = 3, guides = 'auto'))
  }
wrap_plots(cost_plt, nrow =2, ncol = 3) + plot_layout(guides = 'keep')

dev.off()

```


```{r}
runandtestgrts <- function(d, SA_sum, nruns, narus =30){
  d$inclusionPr$stratum <- "Ontario"
  id <- d$att_long$StudyAreaID %>% unique
  ARU_locs <- run_grts_on_BASS(nruns, d, nARUs = narus, idcol = "stratum", os = 0)
  z <-map(1:nruns,~ARU_locs[[.x]]@data %>% filter(panel == "PanelOne") %>% 
  .[["SampleUnitID"]] %>%  as.character)
z_out <- map_df(1:nruns,~ARU_locs[[.x]]@data %>% filter(panel == "PanelOne") %>% mutate(r = .x) )
# print(z_out)

z_200 <- 
z_out %>% group_by(SampleUnitID) %>% 
  summarize(n=n()) %>% ungroup

diff_withSA_draws <- 
z_out %>% right_join(d$att_long, by = "SampleUnitID") %>% 
  # pivot_longer(cols = matches("LC\\d"), values_to = "ha", names_to = "lc") %>% 
  group_by(r, lc, StudyAreaID) %>% 
  summarize(ha = sum(ha)) %>% 
  group_by(r, StudyAreaID) %>% 
  mutate(phab = ha / sum(ha)) %>% ungroup %>% 
  left_join(SA_sum, by = c("StudyAreaID", "lc")) %>% 
  mutate(StudyAreaID = id)
# browser()
errors <- diff_withSA_draws %>% 
  mutate(E = ((phab - pHab_SA))**2,
         ae = abs(phab-pHab_SA)*100) %>% 
  group_by(r) %>% 
  summarize(SSE = sum(E),
            MAE = mean(ae), StudyAreaID = id) 
print(glue::glue("Finished {id}"))
return(list(errors = errors, diff_withSA_draws = diff_withSA_draws, 
            grts_hexes = z_out, grts_res = ARU_locs, 
            id = id))

}

SA_sum <- LC2015_att %>%  
  group_by(StudyAreaID) %>% 
  summarize_at( .vars = vars(matches("^LC\\d.$")), .funs = sum) %>% 
   pivot_longer(cols = matches("LC\\d.$"), names_to = "lc", values_to = "pHab_SA") %>% 
   group_by(StudyAreaID) %>% 
  mutate(pHab_SA = pHab_SA / sum(pHab_SA)) %>%
 
  arrange(StudyAreaID,pHab_SA) %>% 
  mutate(cHAb_SA = cumsum(pHab_SA),
         lcFac = forcats::fct_reorder(lc, pHab_SA),
         lc_n = as.numeric(stringr::str_extract(lc, "\\d\\d") ))%>% 
  left_join(lcc2015_codes, by = c("lc_n" = "LCC_CODE")) %>% 
  mutate(lcc_fac = forcats::fct_reorder(LCC_NAME, pHab_SA)) %>% ungroup()


LCC2015_BASS[[1]]$inclusionPr$stratum <- "Ontario"



exampleGRTS <- run_grts_on_BASS(1, LCC2015_BASS[[1]], nARUs = 30, idcol = "stratum", os = 0)

exampleGRTS_hexes <- allhexes$SampleUnits %>% 
  filter(SampleUnitID %in% exampleGRTS[[1]]@data$SampleUnitID)

saHex <- allhexes$SampleUnits %>% 
  filter(SampleUnitID %in% LCC2015_BASS[[1]]$inclusionPr$SampleUnitID)


ggplot() + 
  geom_sf(data = saHex, fill = NA) +
  geom_sf(data = exampleGRTS_hexes, fill = 'blue') +
  theme_minimal() +
   ggspatial::annotation_scale(location = "bl", width_hint = 0.4)


```


```{r}

test_ <- runandtestgrts(LCC2015_BASS[[1]], SA_sum, nruns = 2 )


results_grts_SA <- map(LCC2015_BASS, runandtestgrts, SA_sum = SA_sum, nruns = 200) %>% purrr::transpose()
errors_df <- results_grts_SA$errors %>% bind_rows()

diff_withSA_draws <- results_grts_SA$diff_withSA_draws %>% bind_rows()

```

```{r}
ggplot(errors_df,aes(SSE, fill = StudyAreaID)) +
  geom_density(alpha = 0.2) +
  theme_minimal() +
  labs(x = "Sum of Squared Error from Study Area (in %)") +
  scale_fill_viridis_d()
```



```{r}
ggplot(errors_df, aes(MAE, fill = StudyAreaID)) +
  geom_density(alpha = 0.2) +
  theme_minimal() +
  labs(x = "Mean Absolute Error from Study Area Percent") +
  facet_wrap(~StudyAreaID, scales = 'free')
```

```{r}

ggplot(diff_withSA_draws, aes(lcc_fac, phab)) + 
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
  geom_point(aes(y = pHab_SA), colour = 'red', shape = "-", size = 10)+
    theme(axis.text.x = element_text(family = 'mono', 
                                   angle= 75, vjust = 1, hjust = 1)) +
  facet_wrap(~StudyAreaID)


# 
# diff_withSA_draws %>% select(StudyAreaID, lcc_fac, pHab_SA) %>% distinct() %>% 
#   group_by(StudyAreaID) %>% 
#   summarize( s = sum(pHab_SA))

```


```{r}
results_grts_SA_100 <- map(LCC2015_BASS, runandtestgrts, SA_sum = SA_sum, nruns = 10, narus = 100) %>% purrr::transpose()
errors_df100 <- results_grts_SA_100$errors %>% bind_rows()

diff_withSA_draws100 <- results_grts_SA_100$diff_withSA_draws %>% bind_rows()
```

```{r}
ggplot(diff_withSA_draws100, aes(lcc_fac, phab)) + 
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
  geom_point(aes(y = pHab_SA), colour = 'red', shape = "-", size = 10)+
    theme(axis.text.x = element_text(family = 'mono', 
                                   angle= 75, vjust = 1, hjust = 1)) +
  facet_wrap(~StudyAreaID)

```



```{r}
p <- ggplot() + 
  geom_sf(data = saHex, fill = NA) +
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
  )

```





```{r, eval=F}
ggsave(p, filename = "output/BASS_hexes.png",  bg = "transparent")
ggsave(p + ggspatial::annotation_scale(location = "bl", width_hint = 0.4),
       filename = "output/BASS_hexes_scale.png")

```



