---
title: "Spatial Works Hexagons"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Spatial Works Hexagons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=F, echo=T}
knitr::opts_chunk$set(
  eval=T,
  collapse = TRUE,
  fig.width = 12,
  fig.height = 10,
  comment = "#>"
)
library(tidyverse)
library(sf)
library(spsurvey)
library(glue)
library(BASSr)
library(raster)
library(rlang)
library(patchwork)
spatialworks <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BaldwinHexLandCov/Data/ExportedDataTables"

files_spatialworks <- list.files(path = spatialworks, pattern = ".csv")

files_study <- files_spatialworks[grepl("Study", x=files_spatialworks)]
files_sample <- files_spatialworks[grepl("Sample", x=files_spatialworks)]
read_SW <- function(lst, x){read_csv(paste(spatialworks, lst[grepl(x,lst)],sep="/" ), col_types = cols())}
FNLCID <- read_SW(files_spatialworks, "CLS_F")
LC15ID <- read_SW(files_spatialworks, "CLS_CLC2015")
LC10ID <- read_SW(files_spatialworks, "CLS_CLC2010")
```

## Load in study areas

```{r}
allhexes <- read_rds(here::here("output/NOntario_BASS_hexes.rds"))
brandtStudyAreas <- read_rds(here::here("output/NONT_HexesWithinBrant.rds"))
StudyAreas <- read_SW(files_study, "StudyAreas") %>% 
# read_csv(paste(spatialworks, files_study[grepl("StudyAreas",files_study)],sep="/" ))  %>% 
  rename(StudyAreaID = StdyAID)

LCC2010 <-  read_SW(files_study, "2010") %>% 
  left_join(StudyAreas, by = "ID")

LCC2015 <- read_SW(files_study, "2015") %>% 
  left_join(StudyAreas, by = "ID")

FNLC <- read_SW(files_study, "FNLC") %>% 
  left_join(StudyAreas, by = "ID")

StudyArea_cost_30arus <- 
  read_rds(here::here("output/2020-02-05_StudyAreaCost.rds"))$StudyArea_CostModel %>% 
  as_tibble %>% dplyr::select(-geometry)
brandtStudyAreas_list <-  brandtStudyAreas$StudyAreaID
StudyArea_LandCover_Cost <- list(
  StudyAreas=allhexes$StudyAreas,
  LCC2010=LCC2010, 
  LCC2015=LCC2015, 
  FNLC=FNLC, 
  BrandtStudyAreas = brandtStudyAreas_list, 
  StudyArea_cost_30arus= StudyArea_cost_30arus)
```

```{r, eval =F}
write_rds(StudyArea_LandCover_Cost, glue::glue("{spatialworks}/StudyAreas_Spatialworks_w_cost.rds"))
```



# Test BASS run on LCC 2015
```{r}
tranx <- function(x)glue::glue("LC{stringr::str_pad(stringr::str_split(x, '_')[[2]],2, pad = 0)}")
brandtStudyAreas_list <-  brandtStudyAreas$StudyAreaID




LC2015_att <- clean_forBass(LCC2015, "CLC15") 

WaterSA <- LC2015_att$StudyAreaID[LC2015_att$D_CLC15 == 18& LC2015_att$LC18/ LC2015_att$TOT_HA>0.6]

sp.sa <- StudyArea_LandCover_Cost$StudyAreas %>% filter(StudyAreaID %in% brandtStudyAreas$StudyAreaID)

sa.cost <- StudyArea_LandCover_Cost$StudyArea_cost_30arus %>% 
  mutate(INLAKE = ifelse(StudyAreaID %in% WaterSA, T, F),
         X = NA, Y = NA) 
  



# 
# ggplot(LC2015_att %>% filter(StudyAreaID %in% WaterSA),
#        aes(LC18/TOT_HA)) + geom_histogram(bins = 20)



LCC2015_BASS <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = LC2015_att, 
                                     att.sp = st_centroid(sp.sa), stratumID = Province,
                                     cost = sa.cost, return_all = T, HexID_ = StudyAreaID, q = T)

LCC2015_BASS$inclusionPr %>% 
  ggplot(aes(LogCost, benefit)) + geom_point()

```



```{r}

plt_SA <- function(d, fill_){
  StudyArea_LandCover_Cost$StudyAreas %>% 
     left_join(d) %>% 
  ggplot() + 
  geom_sf(aes(fill = {{fill_}})) +
  scale_fill_viridis_c() +
     ggspatial::annotation_scale(location = "bl", width_hint = 0.4)

}

plt_SA(LCC2015_BASS$inclusionPr, benefit)
```




## FNLC


```{r}
FNLC_att <- clean_forBass(FNLC, "FNLC")

WaterSA_FNLC <- FNLC_att$StudyAreaID[FNLC_att$D_FNLC == 1& FNLC_att$LC01/ FNLC_att$TOT_HA>0.6]

FNLC_BASS <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = FNLC_att, 
                                     att.sp = st_centroid(sp.sa),stratumID = Province,
                                     cost = sa.cost, return_all = T, HexID_ = StudyAreaID, q = T)




```



```{r}

plt_SA(FNLC_BASS$inclusionPr, benefit)
```

## LC2010
```{r}
CLC10_att <- clean_forBass(LCC2010, "CLC10")


WaterSA_FNLC <- FNLC_att$StudyAreaID[FNLC_att$D_FNLC == 1& FNLC_att$LC01/ FNLC_att$TOT_HA>0.6]

LC10_BASS <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = CLC10_att, 
                                     att.sp = st_centroid(sp.sa),stratumID = Province,
                                     cost = sa.cost, return_all = T, HexID_ = StudyAreaID, q = T)


```



```{r}


plt_SA(LC10_BASS$inclusionPr, benefit)
```



## Far North Dominate Land Cover Class
```{r}
# FNLC_att %>% select_at(.vars = vars(matches("^LC\\d"))) %>% 
#   rowSums() %>% hist
FNLC_names <- StudyArea_LandCover_Cost$StudyAreas %>% 
  right_join(FNLC_att) %>% 
  left_join(FNLCID, by = c("D_FNLC"="SW_ID"))

FNLC_names %>% 
   ggplot() + 
  geom_sf(aes(fill = Class)) +
  scale_fill_viridis_d() +
  labs(title = "Dominant Far North Land Cover", fill = "FNLC")

```

## Land Cover 2015 Dominate Land Cover Class
```{r}
StudyArea_LandCover_Cost$StudyAreas %>% 
  right_join(LC2015_att) %>% 
  left_join(LC15ID, by = c("D_CLC15"="SW_ID")) %>% 
   ggplot() + 
  geom_sf(aes(fill = Class)) +
  scale_fill_viridis_d() +
  labs(title = "Dominant Canadian Land Cover 2015", fill = "CLC2015")
```





## Land Cover 2010 Dominate Land Cover Class
```{r}
StudyArea_LandCover_Cost$StudyAreas %>% 
  right_join(CLC10_att) %>% 
  left_join(LC10ID, by = c("D_CLC10"="SW_ID")) %>% 
   ggplot() + 
  geom_sf(aes(fill = Class)) +
  scale_fill_viridis_d()+
   labs(title = "Dominant Canadian Land Cover 2010", fill = "CLC2010")
```




```{r}
Studyareas_forcompare <- FNLC_names %>% filter(!is.na(Class)) %>% .$StudyAreaID


LCC2015_BASS2 <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = LC2015_att %>% 
                                       filter(StudyAreaID %in% Studyareas_forcompare), 
                                     att.sp = st_centroid(sp.sa %>% 
                                                            filter(StudyAreaID %in% Studyareas_forcompare)),
                                     cost = sa.cost %>% 
                                       filter(StudyAreaID %in% Studyareas_forcompare), 
                                     return_all = T, 
                                     HexID_ = StudyAreaID,stratumID = Province, 
                                      q = T)
FNLC_BASS2 <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = FNLC_att %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), 
                                     att.sp = st_centroid(sp.sa %>% 
                                                            filter(StudyAreaID %in% Studyareas_forcompare)),
                                     cost = sa.cost %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), return_all = T,stratumID = Province, HexID_ = StudyAreaID, q = T)
LC10_BASS2 <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = CLC10_att %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), 
                                     att.sp = st_centroid(sp.sa %>% 
                                                            filter(StudyAreaID %in% Studyareas_forcompare)),
                                     cost = sa.cost %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), return_all = T, 
                                   HexID_ = StudyAreaID,stratumID = Province, q = T)


```




```{r}
plt_SA(LCC2015_BASS2$inclusionPr, scale_ben) +labs(title="Canadian LC 2015") + scale_fill_viridis_c(limits = c(0,1))+ 
  plt_SA(LC10_BASS2$inclusionPr, scale_ben) +labs(title="Canadian LC 2010") + scale_fill_viridis_c(limits = c(0,1))+ 
  plt_SA(FNLC_BASS2$inclusionPr, scale_ben) +labs(title="Far North LC") +  scale_fill_viridis_c(limits = c(0,1))+ 
  plot_layout(guides = 'collect')
```




```{r}

LC2010_atta <- clean_forBass(LCC2010, "CLC10",appended =  "A")

FNLC_LC <- full_join(FNLC_att, LC2010_atta)

FNLC_CLC2010_BASS <- BASSr::full_BASS_run(num_runs = 50, nsamples = 10, 
                                     att = FNLC_LC %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), 
                                     att.sp = st_centroid(sp.sa %>% 
                                                            filter(StudyAreaID %in% Studyareas_forcompare)),
                                     cost = sa.cost %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), return_all = T, 
                                     HexID_ = StudyAreaID, stratumID = Province,q = T)


```




```{r}
plt_SA(FNLC_CLC2010_BASS$inclusionPr, scale_ben) + 
  labs(title="Far North and LC2010 Combined")+  scale_fill_viridis_c(limits = c(0,1))
```


```{r mean_ben-fnlc-lcc}


  
lcc_fnlcben <- (LCC2015_BASS2$inclusionPr$benefit + FNLC_BASS2$inclusionPr$benefit)/2

lcc_fnlc <- LCC2015_BASS2$inclusionPr %>% mutate(beneft = lcc_fnlcben) %>% 
  calculate_inclusion_probs(cost = sa.cost %>% 
                                     filter(StudyAreaID %in% Studyareas_forcompare), 
                            hexagon_benefits = ., HexID = StudyAreaID)


plt_SA(lcc_fnlc, scale_ben) + 
  labs(title="Far North and LC2010 Combined-PostHoc")+  scale_fill_viridis_c(limits = c(0,1))

```



```{r, eval=F}
z <- 2500
lrc <- 
LC2015_att %>% select_at( vars(StudyAreaID,matches("^LC\\d+$"))) %>% 
  mutate_if(is.numeric, ~round(./z,0 )*z) 
lrc_sa <- 
lrc %>% 
  group_by_if(is.numeric) %>% 
  mutate(n=n()) %>% 
  nest(StudyAreaID = c(StudyAreaID)) %>% 
  filter(n>1) %>% arrange(desc(n))

LC2015_att[LC2015_att$StudyAreaID%in% lrc_sa$StudyAreaID[[1]]$StudyAreaID,]$StudyAreaID
LC2015_att[LC2015_att$StudyAreaID%in% lrc_sa$StudyAreaID[[2]]$StudyAreaID,]$StudyAreaID

```

```{r, eval=F}
z2 <- 100
closest_wetland <- 
  LC2015_att %>% select_at( vars(StudyAreaID,matches("^LC14$"))) %>% 
  mutate_if(is.numeric, ~round(./z2,0 )*z2) %>% 
   group_by_if(is.numeric) %>% 
  mutate(n=n()) %>% 
  nest(StudyAreaID = c(StudyAreaID)) %>% 
  filter(n>1) %>% arrange(desc(LC14))
  
  LC2015_att[LC2015_att$StudyAreaID%in% closest_wetland$StudyAreaID[[1]]$StudyAreaID,]$StudyAreaID
  
```




