---
title: "N Ontario Study Areas v1"
author: "David Hope"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{N Ontario Study Areas v1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message =F, warning=F}
knitr::opts_chunk$set(eval=T)
library(BASSr)
library(tidyverse)
library(patchwork)
library(sf)
# library(velox)
library(exactextractr)
library(raster)
lcc2015 <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/lcc2015_hab/NontariobrandtLCC2015_reproj.tif"
spatialworks <- "//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SPATIAL/BaldwinHexLandCov/Data/ExportedDataTables"
r <- raster(lcc2015)
studyareas <- st_read(here::here("output/NOntario_BASS_StudyAreas.shp")) %>%  mutate(StudyAreaID = StdyAID)
brantStudyAreas <- read_rds(here::here("output/NONT_HexesWithinBrant.rds"))
ontario <- read_sf("//int.ec.gc.ca/Shares/C/CWS_ON/Shared_Data/Base_Data/Boundaries/Canada/canada.shp") %>%
  filter(PROV == "ON") %>%
  st_transform(st_crs(studyareas), partial = F, check = T)
StudyArea_LandCover_Cost <- read_rds( glue::glue("{spatialworks}/StudyAreas_Spatialworks_w_cost.rds"))
```

```{r}
ggplot(studyareas %>% filter(StdyAID %in% brantStudyAreas$StudyAreaID)) +
  geom_sf(data = ontario) + 
  geom_sf(fill = 'white')
```



```{r, eval=F}

# vr <- velox(r)
# rsa <- rasterize(studyareas, r, field =  "StdyAID")
f_ <- function(values, coverage_fraction,...){
    d <- as_tibble(values)
    d$cf <- coverage_fraction
    d <- d[!is.na(d$value),]
    # print(head(d))
    # if(length(d)!=1){return(NA)}
    t_ <- sum(d$cf, na.rm=T)
    d %>% 
      group_by(
        value
        # {{idcol}}
        ) %>%
      summarize(n=sum(cf, na.rm=T)) %>%
      ungroup %>%
      # rename(value = {{idcol}}) %>%
      mutate(p = n/t_,
             id = as.character( glue::glue("LC{str_pad(value,2, pad=0)}")) )%>%
      dplyr::select(id, p) %>%
      pivot_wider(names_from = id,
                  values_from = p) %>% 
      mutate(t = length(values), t_noNA = nrow(d))
  }
```


```{r, eval=F}

r1 <- crop(r,studyareas[1,]) %>% mask(.,studyareas[1,])

ex1 <- exact_extract(r, studyareas[1,])
ex2 <- exact_extract(r, studyareas[1:2,],fun = f_, progress = T)


sa1_hex_lcc <- raster::extract(r,studyareas[1,],fun = f_, df = F, sp =F)
    # raster::extract( sa1_lcc,sa1,df=T)#,#fun = f_, df = T, sp =F)
  study_area_lcc2015 <- sa1_hex_lcc %>%
    #sa1_hex_lcc$NontariobrandtLCC2015_reproj %>% f_ %>%
    bind_cols(sa1,.)

  
  
```



```{r, eval=F}
# exall <-  exact_extract(r, studyareas,fun = f_, progress = T)
# write_rds(exall, "../AllStudyAreaExtrac.rds")
# exdf <- bind_rows(exall) %>% bind_cols(studyareas)
# write_rds(exdf, "../AllStudyAreaExtracdf.rds")

```



```{r, fig.width=15, fig.height=12}

all_study_areas <- StudyArea_LandCover_Cost$LCC2015 %>% 
  clean_forBass("CLC15", f_vec = brantStudyAreas$StudyAreaID) %>% 
  left_join(studyareas %>% rename(StudyAreaID = StdyAID))
  # #read_rds(here::here("output/AllStudyAreaExtracdf.rds")) %>% 
  # filter(StdyAID %in% brantStudyAreas$StudyAreaID) %>% 
  # mutate_at(vars(contains("LC")), ~(replace(., is.na(.), 0))) %>% 
  # mutate(StudyAreaID = StdyAID)

ggplot() + 
  geom_sf(
    data = st_as_sf(pivot_longer(all_study_areas,
                                 cols = matches("^LC\\d+$"),
                                 names_to = "LC", 
                                 values_to = "Hab") %>% 
                      group_by(StudyAreaID) %>% 
                      mutate(pHab = Hab / sum(Hab)) %>% 
                      ungroup
                    
                    ),
                    aes(fill = pHab)) +
  facet_wrap(~LC, ncol = 5) +
  scale_fill_viridis_c()
                     

study_area_sf <- st_as_sf(all_study_areas)
hex_centroids <- st_centroid(study_area_sf)

  inlake <- raster::extract(r, hex_centroids,small=T)
  hex_centroids$inlake_YN <- ifelse( inlake == 18, TRUE, FALSE)
```


```{r prov-prob, results='asis'}

all_study_areas %>% dplyr::select(-geometry) %>% 
  pivot_longer(names_to = "LC", values_to = 'habHA', cols = matches("^LC\\d")) %>% 
   group_by(StudyAreaID) %>% 
                      mutate(pHab = habHA / sum(habHA)) %>% 
                      ungroup %>% 
  group_by(LC) %>% 
  summarise(sqkm = sum(habHA) * 0.01 ) %>% ungroup %>% 
  mutate(pHab = round(sqkm/sum(sqkm) * 100, 2)) %>% 
  arrange(desc(pHab)) %>% 
  knitr::kable()

```





```{r, eval=F}



winter_secondary <- read_sf("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/SecondaryRoadsNOntario.shp")
primary_roads <-  read_sf("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BMS_ON/SPATIAL/PrimaryRoadsNOnt.shp")


getroads <- function(sa,  wr,n=F,...){
  cent <- st_centroid(sa)
  print(sa)
  if(isTRUE(n)){
    wr1 <- st_intersection(wr,sa)
    if(nrow(wr1)==0){return(0)}
    return(nrow(wr1))}
  wr1 <- st_intersection(wr,st_buffer(sa, 50000))
  st_distance(cent, wr1, by_element = F) %>% 
     apply(.,1,FUN = min, na.rm=T )
}




  wr <- st_transform(winter_secondary, st_crs(hex_centroids)) 
  pr <- st_transform(primary_roads, st_crs(hex_centroids)) 

  
getroads(study_area_sf[1,], wr, n=F)
getroads(study_area_sf[1,],  wr, n=T)


road_distances <- study_area_sf %>% 
  mutate(sa = split(., 1:nrow(.))) %>% 
  mutate(wr_dist = pmap_dbl(.,getroads, wr=wr,n=F),
         wr_n =  pmap_dbl(.,getroads, wr=wr,n=T),
         pr_dist =  pmap_dbl(.,getroads, wr=pr,n=F),
         pr_n =  pmap_dbl(.,getroads, wr=pr,n=T)) %>% dplyr::select(-sa)

road_distances %>% filter(wr_n >0)
road_distances %>% filter(pr_n >0) %>% 
  st_write("output/primaryroads.kml")

road_distances %>% filter(pr_dist <1000) %>% 
  st_write("output/primaryroads2.kml")
withRoads <- road_distances %>% filter(pr_n >0| wr_n >0)



wr_m <- st_line_merge(wr)
pr_m <- st_line_merge(pr)
all_r <- st_join(dplyr::select(wr_m, OBJECTID,geometry) , pr_m, join = bind_rows)
buff_wr <- st_buffer(wr_m, 1000)
buff_pr <- st_buffer(pr_m, 1000)




```



```{r, eval=F}
# hexes_toexamine <-  read_rds("output/StudyArea_RoadDists.rds") %>% filter(wr_n >0 | pr_n>0)
getroaddensity <- function(hexes,sa, pr,sr,wr, r,idcol,...){
  print(sa)
  hex <- filter(hexes, {{idcol}} == sa)
   pr_h <-st_intersection(pr, hex)# %>% st_area() %>% sum#ifelse(isTRUE(st_contains(hex, pr), sparse =F),, 0)
   sr_h <- st_intersection(sr, hex)# %>% st_area() %>% sum#ifelse(isTRUE(st_contains(hex, sr, sparse =F)), ,0)
   if((nrow(pr_h) == 0) |(nrow(sr_h) == 0 )){
     sr_h_noP <-  sr_h
   } else{   sr_h_noP <- st_difference(sr_h, pr_h) }
   pr_a <- st_area(pr_h) %>% as.numeric %>% sum
   sr_a <- st_area(sr_h_noP) %>% as.numeric %>% sum
   r_h <- st_intersection(r, hex) %>% st_area() %>% as.numeric %>% sum# ifelse(isTRUE(st_contains(hex, r, sparse =F)), ,0)
   wr_h <- st_intersection(wr, hex) %>% st_area() %>% as.numeric %>% sum# ifelse(isTRUE(st_contains(hex, r, sparse =F)), ,0)
   saa <- st_area(hex)
   tibble(saa = saa, 
          pr = ifelse(length(pr_a)==0,0, pr_a),
          sr = ifelse(length(sr_a)==0,0,sr_a), 
          r = ifelse(length(r_h)==0, 0, r_h),
          wr = ifelse(length(wr_h)==0, 0, wr_h),
          StudyArea = as.character(sa) )
}


# write_rds(den_map, "output/road_density_full.rds")


```


## Ontario Road densities

```{r, eval=F}
primary_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/Primary1000.shp") %>% st_transform(st_crs(studyareas))
secondary_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/SecondaryOnlyBuff1k.shp")%>% st_transform(st_crs(studyareas))
road_buffer <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/Roads_1000_PriSec.shp")%>% st_transform(st_crs(studyareas))
winter_buff <- st_read("//int.ec.gc.ca/sys/InGEO/GW/EC1130MigBirds_OiseauxMig/ON_CWS/THEMES/BorealApproach/SANDBOX/dhdev/WinterRoads_Buffer1k.shp")%>% st_transform(st_crs(studyareas))



st_crs(hexes_toexamine[16,]) == st_crs(primary_buffer)
den_map <- map_df( as.character(studyareas$StdyAID), getroaddensity, hexes = studyareas, wr = winter_buff,
               pr= primary_buffer,sr = secondary_buffer, r = road_buffer, idcol = StdyAID) 


getroaddensity(hexes = studyareas, wr = winter_buff,sa = "ONT_SA_0022",
               pr= primary_buffer,sr = secondary_buffer, r = road_buffer, idcol = StdyAID)

write_rds(den_map, "output/road_density_byHex_full.rds")


```


```{r, fig.width=12, fig.height=10}
sa_bcr <- read_rds(here::here("output/studyareas_by_eco_bcr.rds"))
den_map <- read_rds(here::here("output/road_density_byHex_full.rds"))


den_map_p <- den_map %>% filter(StudyArea %in% unique(as.character(sa_bcr$StudyAreaID) )) %>% 
  mutate(prim = pr / saa, sec = sr / saa, allroads = r/saa,
         wint = wr /saa ) %>% right_join(studyareas, by = c("StudyArea"))


pl <- ggplot(data= st_as_sf(den_map_p)) + scale_fill_viridis_c(limits = c(0,1))# + geom_sf(fill = alpha('white', 0.), colour = 'black')
(pl + geom_sf(aes(fill = prim)) +  pl + geom_sf(aes(fill = wint)) )/
  ( pl + geom_sf(aes(fill = sec) ) +pl + geom_sf(aes(fill = allroads))  )


```

```{r, fig.width=12, fig.height=10}

ggplot(den_map_p) + geom_histogram(aes(prim), binwidth = 0.05) + 
  labs(x = "Proportion of SA covered by Primary Roads plus buffer", y = "Number of Study Areas") +
  lims(x = c(-.05,1.1))+
ggplot(den_map_p) + geom_histogram(aes(sec), binwidth = 0.05) + 
  labs(x = "Proportion of SA covered by Secondary Roads plus buffer", y = "Number of Study Areas")+
  lims(x = c(-.05,1.1))+
ggplot(den_map_p) + geom_histogram(aes(wint), binwidth = 0.05) + 
  labs(x = "Proportion of SA covered by Winter Roads plus buffer", y = "Number of Study Areas")+
  lims(x = c(-.05,1.1))+
ggplot(den_map_p) + geom_histogram(aes(allroads), binwidth = 0.05) + 
  labs(x = "Proportion of SA covered by all roads plus buffer", y = "Number of Study Areas")+
  lims(x = c(-.05,1.1))

```



```{r}
road_distances <- read_rds(here::here("output/StudyArea_RoadDists.rds"))
```

```{r}

hist(road_distances$wr_dist/1000)
hist(road_distances$pr_dist/1000, breaks = 100)
hist(log(road_distances$wr_n), breaks = 100)
hist(road_distances$pr_n)

rdn <- 
road_distances %>% 
  mutate(n = log(wr_n)) %>% 
  group_by(n) %>% 
  summarize(n_h = n()) %>% 
  ungroup %>% 
  mutate(n = exp(n)) %>% 
  arrange(desc(n_h))

ggplot(rdn %>% 
         filter(n>0&n<10000), aes(n, n_h)) + geom_point() 


rdp <- ggplot(road_distances)
```

```{r road-plt, fig.width=18, fig.height=12}
(rdp + geom_sf(aes(fill = pr_dist/1000)) + labs(title = "Distance to Primary Roads", fill = "Dist (km)")+
  rdp + geom_sf(aes(fill = wr_dist/1000)) + labs(title = "Distance to Secondary/Winter Roads", fill = "Dist (km)")) / 
  (rdp + geom_sf(aes(fill = pr_n)) + labs(title = "Number Primary Roads in SA", fill = "N")+
  rdp + geom_sf(aes(fill = log(wr_n))) + 
    labs(title = "Number Secondary Roads in SA", fill = "N"))


```



```{r}
study_area_hexes_w_cost <- road_distances %>% 
   filter(StdyAID %in% brantStudyAreas$StudyAreaID) %>% 
    mutate(
           RawCost = case_when(
             (wr_n > 100 & pr_n ==1)~1000,
             (pr_dist < 50000)~(5*160*1.5*5),
             (wr_dist < 50000 )~(5*160*2*5),
             (wr_dist > 50000 & pr_dist>50000)~(5*160*5*5),
             TRUE~NA_real_
           )) %>%
    bind_cols(as_tibble(st_coordinates(hex_centroids))) %>% 
  mutate(INLAKE = F)


ggplot(study_area_hexes_w_cost) + geom_sf(aes(fill = RawCost))


```



```{r, warning=F}
sa_bcr <- read_rds(here::here("output/studyareas_by_eco_bcr.rds"))

OntBrant <- read_rds(system.file("extdata",package = "BASSr", "ontario_brandt.rds")) # From the BMS Ontario scripts
cost_brandt <- read_rds(here::here("output/cost_estimates.rds"))
sa_w_cost <- all_study_areas %>% 
  left_join(cost_brandt) %>% dplyr::select(-x) %>% 
  mutate(RawCost = total_cost) %>% 
  mutate(INLAKE = ifelse(LC18/TOT_HA>0.5, T, F),
         Province = "ON")

sa_w_cost[c("X", "Y")] <- st_coordinates(st_centroid(st_as_sf(all_study_areas)))
 
```

```{r water}
ggplot(all_study_areas %>% st_as_sf , aes(fill = LC18)) + geom_sf() +
  scale_fill_viridis_c()
```



```{r}
left_join(all_study_areas, as_tibble(sa_bcr), by = "StudyAreaID") %>% 
  dplyr::select(-x) %>% 
  st_as_sf() %>% 
  ggplot() +
  geom_sf(aes(fill = BCR_Name)) +
  scale_fill_viridis_d()
```


```{r, warning=F, message=F}
BASSres <- full_BASS_run(num_runs = 100, nsamples = 10, 
                         att = sa_w_cost ,
                         q = T,
                         att.sp = st_centroid(st_as_sf(sa_w_cost)), stratumID = Province,
                         cost = sa_w_cost, HexID_ = StudyAreaID, return_all = T )
```



```{r}
ggplot(left_join(studyareas, BASSres$inclusionPr)) + geom_sf(aes(fill = benefit))
```

```{r,fig.width=12, fig.height=8}
ggplot(left_join(studyareas, BASSres$inclusionPr)) + geom_sf(aes(fill = ScLogCost)) +
ggplot(left_join(studyareas, BASSres$inclusionPr)) + geom_sf(aes(fill = scale_ben)) +
  plot_layout(guides = 'collect')

```


```{r}
ggplot(left_join(studyareas, BASSres$inclusionPr)) + geom_sf(aes(fill = inclpr))
```



```{r, eval=F}
BASSres$inclusionPr$stratum <- "Ontario"
SAs <- run_grts_on_BASS(n_grts_tests = 200,study_area_results =  BASSres,
                        nARUs =  80,os =  0.5,idcol =  "stratum")
write_rds(SAs, "output/Ontario_StudyareaGRTS.rds")
```

```{r}

SAs <- read_rds(here::here("output/Ontario_StudyareaGRTS.rds"))

z <-map(1:200,~SAs[[.x]]@data %>% filter(panel == "PanelOne") %>% 
  .[["StdyAID"]] %>%  as.character)
z_out <- map_df(1:200,~SAs[[.x]]@data %>% filter(panel == "PanelOne") %>% mutate(r = .x) )

z_200 <- 
z_out %>% group_by(StudyAreaID) %>% 
  summarize(n=n())


sampleont <- dplyr::filter(.data = left_join(studyareas, BASSres$inclusionPr), StudyAreaID %in% z_200$StudyAreaID)

sb <- spbalance(SAs[[1]], study_area_hexes_w_cost)

ggplot(sampleont) + geom_sf(data = st_as_sf(sa_w_cost),fill=NA) + 
  geom_sf(aes(fill = inclpr))


ggplot(studyareas %>% left_join(z_200)) + geom_sf(fill=NA) + 
  geom_sf(aes(fill = n/200)) +scale_fill_viridis_c() +
  labs(fill = "", title = "Proportion of 200 grts SA chosen")

grts_er <- left_join(z_out,sa_bcr, by = c( "StudyAreaID") )

grts_er %>% group_by(REGION_NAM, r) %>% 
  summarize(n =n()) %>% 
  ggplot(aes(REGION_NAM, n)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "", y = "ARUS of 80")


grts_er %>% 
  mutate(plan = ifelse(is.na(PLAN_NAME), MU_NAME, PLAN_NAME)) %>% 
  group_by(plan, r) %>% 
  summarize(n =n()) %>% 
  ggplot(aes(plan, n)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "", y = "Study Areas of 80")

```






