# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sum of vector
#'
#' @param x A vector
#' @export
sumC <- function(x) {
    .Call(`_BASSr_sumC`, x)
}

#' Opposite signs True or false
#'
#' @param x a double value
#' @param y an integer
#' @export
oppositeSigns <- function(x, y) {
    .Call(`_BASSr_oppositeSigns`, x, y)
}

#' The internal BASSr benefit algorithm
#'
#' @param hex A vector of land cover values
#' @param sample a vector of land cover values from random sample
#' @param total a vector of land cover values from total of study area
#' @param printDets logical - should you print the details - messy for now.
#' @export
speedbass <- function(hex, sample, total, printDets = FALSE) {
    .Call(`_BASSr_speedbass`, hex, sample, total, printDets)
}

#' Run speed bass on all hexagons and all samples
#'
#' @param hexes Matrix of hexagon land covers. Rows are hexagons, columns are land cover types
#' @param samples Matrix of hexagon land covers from random sample. Rows are hexagons, columns are land cover types
#' @param total Vector of total land cover. values are individual land cover types
#' @export
allhexes <- function(hexes, samples, total, printDets = FALSE) {
    .Call(`_BASSr_allhexes`, hexes, samples, total, printDets)
}

#' Add a number to a sum of vector
#'
#' @param x A vector
#' @param h a nuber to add
#' @export
sumH <- function(x, h) {
    .Call(`_BASSr_sumH`, x, h)
}

